version: "3.9"

services:

  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - back

  back:
    container_name: back
    build:
      context: ./back
    command: uwsgi --socket :8000 --http :8001  --module mainproject.wsgi --py-autoreload 1 -b 32768
    expose: 
      - 8000
    volumes:
      - ./back:/server/

  front:
    container_name: front
    build:
      context: ./front
    command: 'sh /app/start.sh'
    volumes:
      - ./front:/app/:cached
      - ./front/node_modules:/app/node_modules
    ports:
      - "8080:8080"